name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run Prettier and check commits messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Run Prettier
        run: bun run fmt

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v6
